### ISSUE TITLE
is the preset of the map generator missing?

### ISSUE THREAD

**Issue by GIKExe** [Tobicoby/stranded_block_2#1]
![image](https://github.com/user-attachments/assets/fe7c49e1-311d-4e7f-99e3-3c4844351621)
"strandedblock" is not in the list

**Comment by Tobicoby** [comment]
have you enabled the mod and restarted?
![Screenshot 2024-11-11 152317](https://github.com/user-attachments/assets/3f13347b-395b-45ae-9250-bbbc6fed1e8a)

the language has been set to "some"(idk) language to test for any missing locales
![Screenshot 2024-11-11 152136](https://github.com/user-attachments/assets/2488d32d-ec23-4995-b75d-115899299727)

for me stranded block appears
